env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - make build-frontend

builds:
  - binary: listmonk
    main: ./cmd
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})" -X "main.versionString={{ .Tag }}"

    hooks:
      # stuff executables with static assets.
      post: make pack-bin BIN={{ .Path }}

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE

dockers:
  - goos: linux
    goarch: amd64
    ids:
    - listmonk
    image_templates:
    - "listmonk/listmonk:latest"
    - "listmonk/listmonk:{{ .Tag }}"
    - "ghcr.io/knadh/{{ .ProjectName }}:latest"
    - "ghcr.io/knadh/{{ .ProjectName }}:{{ .Tag }}"
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/knadh/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/knadh/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=AGPL-3.0
    dockerfile: Dockerfile
    extra_files:
    - config.toml.sample
    - config-demo.toml
